Formula2/Controllers/CompetitionController.cs
using System.Diagnostics;
using DataAccess.Data;
using DataAccess.Repository;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace Formula2.Controllers
{
    public class CompetitionController : Controller
    {
        private readonly IUnitOfWork _db;

        public CompetitionController(IUnitOfWork unitOfWork)
        {
            _db = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert()
        {
            return View();
        }
    }
}

Formula2/Controllers/DriverController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Models;
using Newtonsoft.Json;

namespace Formula2.Controllers
{
    public class DriverController : Controller
    {
        private readonly IUnitOfWork _db;

        public DriverController(IUnitOfWork unitOfWork)
        {
            _db = unitOfWork;
        }

        #region View Calls

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert()
        {
            return View();
        }

        #endregion


        #region APICalls

        [HttpPost]
        public async Task<IActionResult> CreateDriver([FromForm] string driver)
        {
            using var transaction = _db.GetContext().Database.BeginTransaction();
            try
            {
                if (!string.IsNullOrEmpty(driver))
                {
                    var driverObj = JsonConvert.DeserializeObject<Driver>(driver);

                    //Add creator indentity
                    _db.Driver.Add(driverObj);
                    _db.Save();

                    int driverId = driverObj.Id;
                }
                else
                {
                    throw new Exception("Información no capturada correctamente");
                }

                transaction.Commit();
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(new { error = ex.Message });
            }
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Driver> objDriversList = _db.Driver.GetAll(null).ToList();
            return Json(new { data = objDriversList });
        }

        #endregion
    }
}

Formula2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Formula2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Formula2.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-primary mb-3">
            <div class="container-fluid ms-4">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Formula2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Competition" asp-action="Index">Competiciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Driver" asp-action="Index">Pilotos</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Formula2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/2.3.3/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>